on: [push]

jobs:
  create_campsite_post:
    runs-on: ubuntu-latest
    name: Create Campsite post
    steps:
      - name: Create Campsite post
        id: campsite
        uses: campsite/campsite-github-action@v1.0.0
        with:
          campsite-api-key: ${{ secrets.CAMPSITE_TOKEN }}
          action-type: post
          channel-id: ${{ secrets.CAMPSITE_CHANNEL_ID }}
          title: "Hello from GitHub Actions"
          content: "This is a *test post*"
      - name: Get the output URL
        run: echo "The URL is ${{ steps.campsite.outputs.post_url }}"
