on: [push]

jobs:
  create_campsite_post:
    runs-on: ubuntu-latest
    name: Create Campsite post
    steps:
      - name: Create Campsite post
        id: campsite
        uses: campsite/campsite-github-action@v0.1.0
        with:
          api_key: ${{ secrets.CAMPBOT_API_KEY }}
          action_type: create_post
          channel_id: 050d8hh4a1dx # "Integrations testing" channel
          title: "Hello from GitHub Actions"
          content: "This is a *test post*"
      - name: Get the output URL
        run: echo "The post URL is ${{ steps.campsite.outputs.post_url }}"
